INSERT INTO resources (title, resource_url, description, resource_image_url, rating, user_id)
VALUES ('Codeacademy', 'https://www.codecademy.com/', 'harder buy paint inside kind planning appearance iron spent give smaller truck camera hit noon morning dear character famous wore article produce still fence decide while place been let border level law afternoon band rising hat improve snake far managed eventually spell pocket favorite carried each full closely pot threw daily stranger coming was easily from industrial stomach ourselves tower wife modern plates onto look wheel knew independent breathing few greater mission distance have column construction room sort wonderful important unhappy composition consonant waste donkey clear particular eight being simplest hunter manner cat lucky progress prize potatoes lonely dirty hung useful feed given combine oldest top green bat square rocket pack card weak tune noise myself form thrown impossible kitchen vast bad where fully her exist telephone differ describe now funny yes parts value account gentle applied wear finally ancient construction airplane gray large buffalo different beside damage life helpful lift personal', 'https://www.codecademy.com/webpack/e908164f059c81faded2866ab983e950.png', 5, 1);

INSERT INTO resources (title, resource_url, description, resource_image_url, rating, user_id)
VALUES ('Udemy', 'https://www.udemy.com/', 'harder buy paint inside kind planning appearance iron spent give smaller truck camera hit noon morning dear character famous wore article produce still fence decide while place been let border level law afternoon band rising hat improve snake far managed eventually spell pocket favorite carried each full closely pot threw daily stranger coming was easily from industrial stomach ourselves tower wife modern plates onto look wheel knew independent breathing few greater mission distance have column construction room sort wonderful important unhappy composition consonant waste donkey clear particular eight being simplest hunter manner cat lucky progress prize potatoes lonely dirty hung useful feed given combine oldest top green bat square rocket pack card weak tune noise myself form thrown impossible kitchen vast bad where fully her exist telephone differ describe now funny yes parts value account gentle applied wear finally ancient construction airplane gray large buffalo different beside damage life helpful lift personal', 'https://img-a.udemycdn.com/course/240x135/629302_8a2d_2.jpg', 3, 1);

INSERT INTO resources (title, resource_url, description, resource_image_url, rating, user_id)
VALUES ('Lighthouse Labs', 'https://www.lighthouselabs.ca/', 'harder buy paint inside kind planning appearance iron spent give smaller truck camera hit noon morning dear character famous wore article produce still fence decide while place been let border level law afternoon band rising hat improve snake far managed eventually spell pocket favorite carried each full closely pot threw daily stranger coming was easily from industrial stomach ourselves tower wife modern plates onto look wheel knew independent breathing few greater mission distance have column construction room sort wonderful important unhappy composition consonant waste donkey clear particular eight being simplest hunter manner cat lucky progress prize potatoes lonely dirty hung useful feed given combine oldest top green bat square rocket pack card weak tune noise myself form thrown impossible kitchen vast bad where fully her exist telephone differ describe now funny yes parts value account gentle applied wear finally ancient construction airplane gray large buffalo different beside damage life helpful lift personal', 'https://www.lighthouselabs.ca/assets/illustration/online_courses-7dd116a74198269dc07e067296259d0b23e870ffd107cba0f194c3bd7d3ecf35.png', 4, 1);

INSERT INTO resources (title, resource_url, description, resource_image_url, rating, user_id)
VALUES ('Lazy Gourmet', 'https://www.lazygourmet.ca/menus/classroom-events/?gclid=Cj0KCQjwjer4BRCZARIsABK4QeW_9BHbg7eVgfR7xxp5NFCZs6G__Cw42xP-aXyv3ha6fIx5bFXP9LEaAhfrEALw_wcB', 'harder buy paint inside kind planning appearance iron spent give smaller truck camera hit noon morning dear character famous wore article produce still fence decide while place been let border level law afternoon band rising hat improve snake far managed eventually spell pocket favorite carried each full closely pot threw daily stranger coming was easily from industrial stomach ourselves tower wife modern plates onto look wheel knew independent breathing few greater mission distance have column construction room sort wonderful important unhappy composition consonant waste donkey clear particular eight being simplest hunter manner cat lucky progress prize potatoes lonely dirty hung useful feed given combine oldest top green bat square rocket pack card weak tune noise myself form thrown impossible kitchen vast bad where fully her exist telephone differ describe now funny yes parts value account gentle applied wear finally ancient construction airplane gray large buffalo different beside damage life helpful lift personal', 'https://www.lazygourmet.ca/wp-content/uploads/classroom-banner.jpg', 1, 2);


INSERT INTO resources (title, resource_url, description, resource_image_url, rating, user_id)
VALUES ('Delish', 'https://www.delish.com/cooking/g32146845/online-cooking-classes/', 'harder buy paint inside kind planning appearance iron spent give smaller truck camera hit noon morning dear character famous wore article produce still fence decide while place been let border level law afternoon band rising hat improve snake far managed eventually spell pocket favorite carried each full closely pot threw daily stranger coming was easily from industrial stomach ourselves tower wife modern plates onto look wheel knew independent breathing few greater mission distance have column construction room sort wonderful important unhappy composition consonant waste donkey clear particular eight being simplest hunter manner cat lucky progress prize potatoes lonely dirty hung useful feed given combine oldest top green bat square rocket pack card weak tune noise myself form thrown impossible kitchen vast bad where fully her exist telephone differ describe now funny yes parts value account gentle applied wear finally ancient construction airplane gray large buffalo different beside damage life helpful lift personal', 'https://scontent-sea1-1.cdninstagram.com/v/t51.2885-15/sh0.08/e35/s640x640/89967265_343560186588015_5308279621627816263_n.jpg?_nc_ht=scontent-sea1-1.cdninstagram.com&_nc_cat=103&_nc_ohc=I2VoCZqNmagAX-DWidE&oh=5f6a024baccc92c1c55891e8395ed2ea&oe=5F445093', 3, 2);

